const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const order = [
  "plugin/src/modules/utils.js",
  "plugin/src/modules/inspect.js",
  "plugin/src/modules/creators.js",
  "plugin/src/modules/clone.js",
  "plugin/src/modules/exportOps.js",
  "plugin/src/modules/events.js",
  "plugin/src/modules/dispatcher.js",
  "plugin/src/modules/runtime.js",
];

const banner = `// AUTO-GENERATED by scripts/build-plugin.js. Do not edit directly.\n// Modules are concatenated in this order:\n// ${order.join("\n// ")}\n`;

const parts = order.map((relative) => {
  const file = path.join(root, relative);
  const content = fs.readFileSync(file, "utf8");
  return `// ===== ${relative} =====\n${content}`;
});

const out = path.join(root, "plugin/src/code.js");
fs.writeFileSync(out, `${banner}\n${parts.join("\n\n")}\n`);
console.log(`Built ${out}`);
