// AUTO-GENERATED by scripts/build-plugin.js. Do not edit directly.
// Modules are concatenated in this order:
// plugin/src/modules/utils.js
// plugin/src/modules/inspect.js
// plugin/src/modules/creators.js
// plugin/src/modules/clone.js
// plugin/src/modules/exportOps.js
// plugin/src/modules/events.js
// plugin/src/modules/dispatcher.js
// plugin/src/modules/runtime.js

// ===== plugin/src/modules/utils.js =====
const state = {
  bridgeUrl: "http://localhost:3131",
  secret: "",
  timer: null,
};

function log(message) {
  figma.ui.postMessage({ type: "log", message });
}

function headers() {
  const value = { "content-type": "application/json" };
  if (state.secret) value["x-figma-bridge-secret"] = state.secret;
  return value;
}

async function loadFont(fontName) {
  if (fontName && typeof fontName === "object" && fontName.family && fontName.style) {
    await figma.loadFontAsync(fontName);
    return fontName;
  }
  const fallback = { family: "Inter", style: "Regular" };
  await figma.loadFontAsync(fallback);
  return fallback;
}

async function loadDefaultFonts() {
  await loadFont({ family: "Inter", style: "Regular" });
  await loadFont({ family: "Inter", style: "Bold" });
}

function findNode(id) {
  const node = figma.getNodeById(id);
  if (!node) throw new Error(`Node not found: ${id}`);
  return node;
}

function toHex(paint) {
  if (!paint || paint.type !== "SOLID" || !paint.color) return null;
  const channel = (value) => Math.round(value * 255).toString(16).padStart(2, "0");
  return `#${channel(paint.color.r)}${channel(paint.color.g)}${channel(paint.color.b)}`;
}

function solid(hex) {
  const clean = String(hex || "#ffffff").replace("#", "");
  const n = Number.parseInt(clean.length === 3 ? clean.split("").map((c) => c + c).join("") : clean, 16);
  return { type: "SOLID", color: { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255 } };
}

function gradient(spec) {
  var stops = spec.stops || [
    { position: 0, color: "#000000" },
    { position: 1, color: "#ffffff" },
  ];
  return {
    type: spec.gradientType || spec.type || "GRADIENT_LINEAR",
    gradientTransform: spec.gradientTransform || [
      [1, 0, 0],
      [0, 1, 0],
    ],
    gradientStops: stops.map(function (stop) {
      var color = solid(stop.color).color;
      return {
        position: stop.position,
        color: { r: color.r, g: color.g, b: color.b, a: stop.opacity !== undefined ? stop.opacity : 1 },
      };
    }),
  };
}

function makePaint(spec) {
  if (!spec) return solid("#ffffff");
  if (typeof spec === "string") return solid(spec);
  if (spec.type === "SOLID") return solid(spec.color || spec.hex || "#ffffff");
  if (String(spec.type || "").indexOf("GRADIENT") === 0) return gradient(spec);
  return solid(spec.color || spec.hex || "#ffffff");
}

function makePaints(value, fallback) {
  var source = value !== undefined && value !== null ? value : fallback;
  if (Array.isArray(source)) return source.map(makePaint);
  return [makePaint(source)];
}

function applyVariableBinding(node, spec) {
  if (!spec.variableBindings || typeof node.setBoundVariable !== "function") return;
  for (const binding of spec.variableBindings) {
    const variable = figma.variables.getVariableById(binding.variableId);
    if (!variable) throw new Error(`Variable not found: ${binding.variableId}`);
    node.setBoundVariable(binding.field, variable);
  }
}

function applyGeometry(node, spec) {
  if ("resize" in node && (spec.width || spec.height)) node.resize(spec.width || node.width, spec.height || node.height);
  if ("x" in node && typeof spec.x === "number") node.x = spec.x;
  if ("y" in node && typeof spec.y === "number") node.y = spec.y;
  if ("opacity" in node && typeof spec.opacity === "number") node.opacity = spec.opacity;
  if ("rotation" in node && typeof spec.rotation === "number") node.rotation = spec.rotation;
  if ("cornerRadius" in node && typeof spec.cornerRadius === "number") node.cornerRadius = spec.cornerRadius;
}

function applyStyle(node, spec) {
  if ("fills" in node && (spec.fill || spec.fills || spec.background)) node.fills = makePaints(spec.fills || spec.fill || spec.background);
  if ("strokes" in node && (spec.stroke || spec.strokes)) node.strokes = makePaints(spec.strokes || spec.stroke);
  if ("strokeWeight" in node && typeof spec.strokeWeight === "number") node.strokeWeight = spec.strokeWeight;
  if ("effects" in node && Array.isArray(spec.effects)) node.effects = spec.effects;
  applyVariableBinding(node, spec);
}

function applyAutoLayout(frame, spec) {
  if (!spec.autoLayout) return;
  frame.layoutMode = spec.autoLayout.layoutMode || "VERTICAL";
  frame.primaryAxisSizingMode = spec.autoLayout.primaryAxisSizingMode || "FIXED";
  frame.counterAxisSizingMode = spec.autoLayout.counterAxisSizingMode || "FIXED";
  frame.primaryAxisAlignItems = spec.autoLayout.primaryAxisAlignItems || frame.primaryAxisAlignItems;
  frame.counterAxisAlignItems = spec.autoLayout.counterAxisAlignItems || frame.counterAxisAlignItems;
  frame.itemSpacing = spec.autoLayout.itemSpacing || 0;
  frame.paddingTop = spec.autoLayout.paddingTop || 0;
  frame.paddingRight = spec.autoLayout.paddingRight || 0;
  frame.paddingBottom = spec.autoLayout.paddingBottom || 0;
  frame.paddingLeft = spec.autoLayout.paddingLeft || 0;
}

function bytesFromBase64(data) {
  const clean = String(data || "").replace(/^data:[^,]+,/, "");
  const binary = atob(clean);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}


// ===== plugin/src/modules/inspect.js =====
function firstSolidHex(node, property) {
  const paints = node[property];
  if (!Array.isArray(paints)) return null;
  const solidPaint = paints.find((paint) => paint.type === "SOLID");
  return toHex(solidPaint);
}

function summarizeVariableBindings(node) {
  const boundVariables = node.boundVariables || {};
  const output = {};
  for (const key of Object.keys(boundVariables)) {
    const value = boundVariables[key];
    output[key] = Array.isArray(value)
      ? value.map((entry) => ({ id: entry.id, type: entry.type }))
      : { id: value.id, type: value.type };
  }
  return output;
}

function summarizeNode(node, depth = 0, maxDepth = 3) {
  const summary = { id: node.id, name: node.name, type: node.type };

  if ("x" in node) summary.x = node.x;
  if ("y" in node) summary.y = node.y;
  if ("width" in node) summary.width = node.width;
  if ("height" in node) summary.height = node.height;
  if ("opacity" in node) summary.opacity = node.opacity;
  if ("rotation" in node) summary.rotation = node.rotation;
  if ("fills" in node) summary.fill = firstSolidHex(node, "fills");
  if ("strokes" in node) summary.stroke = firstSolidHex(node, "strokes");
  if ("effects" in node) summary.effects = node.effects;
  if ("cornerRadius" in node && typeof node.cornerRadius === "number") summary.cornerRadius = node.cornerRadius;
  if (node.boundVariables) summary.boundVariables = summarizeVariableBindings(node);
  if ("layoutMode" in node) {
    summary.autoLayout = {
      layoutMode: node.layoutMode,
      primaryAxisSizingMode: node.primaryAxisSizingMode,
      counterAxisSizingMode: node.counterAxisSizingMode,
      primaryAxisAlignItems: node.primaryAxisAlignItems,
      counterAxisAlignItems: node.counterAxisAlignItems,
      itemSpacing: node.itemSpacing,
      paddingTop: node.paddingTop,
      paddingRight: node.paddingRight,
      paddingBottom: node.paddingBottom,
      paddingLeft: node.paddingLeft,
    };
  }
  if (node.type === "TEXT") {
    summary.text = node.characters;
    summary.fontSize = node.fontSize;
    summary.fontName = node.fontName;
    summary.lineHeight = node.lineHeight;
    summary.letterSpacing = node.letterSpacing;
    summary.textAlignHorizontal = node.textAlignHorizontal;
    summary.textAlignVertical = node.textAlignVertical;
  }
  if ("children" in node && depth < maxDepth) {
    summary.children = node.children.map((child) => summarizeNode(child, depth + 1, maxDepth));
  }
  return summary;
}

async function getColorVariables() {
  const locals = await figma.variables.getLocalVariablesAsync("COLOR");
  return locals.map((variable) => ({
    id: variable.id,
    key: variable.key,
    name: variable.name,
    collectionId: variable.variableCollectionId,
    resolvedType: variable.resolvedType,
    valuesByMode: variable.valuesByMode,
  }));
}

async function inspectSelection(payload) {
  return { selection: figma.currentPage.selection.map((node) => summarizeNode(node, 0, payload.maxDepth || 3)) };
}

async function inspectNode(payload) {
  return summarizeNode(findNode(payload.nodeId), 0, payload.maxDepth || 3);
}


// ===== plugin/src/modules/creators.js =====
function withDefaults(spec, defaults) {
  var out = {};
  var key;
  for (key in spec) out[key] = spec[key];
  for (key in defaults) {
    if (out[key] === undefined || out[key] === null) out[key] = defaults[key];
  }
  return out;
}

async function createTextNode(spec, parent) {
  const node = figma.createText();
  node.name = spec.name || "Text";
  node.fontName = await loadFont(spec.fontName || { family: "Inter", style: spec.bold ? "Bold" : "Regular" });
  node.fontSize = spec.fontSize || 32;
  if (spec.lineHeight) node.lineHeight = spec.lineHeight;
  if (spec.letterSpacing) node.letterSpacing = spec.letterSpacing;
  if (spec.textAlignHorizontal) node.textAlignHorizontal = spec.textAlignHorizontal;
  if (spec.textAlignVertical) node.textAlignVertical = spec.textAlignVertical;
  if (spec.textCase) node.textCase = spec.textCase;
  node.characters = spec.characters || spec.text || "Text";
  node.fills = makePaints(spec.fills || spec.fill || spec.color, "#111111");
  applyStyle(node, spec);
  if (spec.width) node.resize(spec.width, node.height);
  if (typeof spec.x === "number") node.x = spec.x;
  if (typeof spec.y === "number") node.y = spec.y;
  parent.appendChild(node);
  return node;
}

async function createRectangleNode(spec, parent) {
  const node = figma.createRectangle();
  node.name = spec.name || "Rectangle";
  applyGeometry(node, withDefaults(spec, { width: 100, height: 100 }));
  applyStyle(node, withDefaults(spec, { fill: "#cccccc" }));
  parent.appendChild(node);
  return node;
}

async function createEllipseNode(spec, parent) {
  const node = figma.createEllipse();
  node.name = spec.name || "Ellipse";
  applyGeometry(node, withDefaults(spec, { width: 100, height: 100 }));
  applyStyle(node, withDefaults(spec, { fill: "#cccccc" }));
  parent.appendChild(node);
  return node;
}

async function createImageNode(spec, parent) {
  if (!spec.imageBytes && !spec.imageHash) throw new Error("Image node needs imageBytes (base64) or imageHash");
  const hash = spec.imageHash || figma.createImage(bytesFromBase64(spec.imageBytes)).hash;
  const node = figma.createRectangle();
  node.name = spec.name || "Image";
  applyGeometry(node, withDefaults(spec, { width: 600, height: 600 }));
  node.fills = [{ type: "IMAGE", imageHash: hash, scaleMode: spec.scaleMode || "FILL" }];
  if (spec.strokes) node.strokes = makePaints(spec.strokes);
  if (spec.effects) node.effects = spec.effects;
  if (typeof spec.cornerRadius === "number") node.cornerRadius = spec.cornerRadius;
  parent.appendChild(node);
  return node;
}

async function createFrameFromSpec(spec, parent) {
  const frame = figma.createFrame();
  frame.name = spec.name || "Generated Frame";
  applyGeometry(frame, withDefaults(spec, { width: 1080, height: 1350 }));
  applyStyle(frame, withDefaults(spec, { fill: spec.background || "#ffffff" }));
  applyAutoLayout(frame, spec);
  parent.appendChild(frame);
  for (const child of spec.children || []) {
    await createNodeFromSpec(child, frame);
  }
  return frame;
}

async function createNodeFromSpec(spec, parent) {
  if (!spec || typeof spec !== "object") throw new Error("Invalid node spec");
  if (spec.type === "TEXT") return createTextNode(spec, parent);
  if (spec.type === "FRAME") return createFrameFromSpec(spec, parent);
  if (spec.type === "RECTANGLE") return createRectangleNode(spec, parent);
  if (spec.type === "ELLIPSE") return createEllipseNode(spec, parent);
  if (spec.type === "IMAGE") return createImageNode(spec, parent);
  throw new Error(`Unsupported spec node type: ${spec.type}`);
}

async function createFromSpec(payload) {
  await loadDefaultFonts();
  const node = await createNodeFromSpec(payload.spec, figma.currentPage);
  figma.viewport.scrollAndZoomIntoView([node]);
  return { nodeId: node.id, name: node.name };
}

async function createPromoFrame(payload) {
  await loadDefaultFonts();
  const width = payload.width || 1080;
  const spec = {
    type: "FRAME",
    name: payload.name || "AI Promo Frame",
    width,
    height: payload.height || 1350,
    fill: payload.background || "#101820",
    autoLayout: { layoutMode: "VERTICAL", paddingTop: 96, paddingRight: 72, paddingBottom: 72, paddingLeft: 72, itemSpacing: 28 },
    children: [
      { type: "TEXT", name: "Badge", text: payload.badge || "PROMO TOPUP", fontSize: 28, bold: true, fill: payload.accent || "#ffcc33" },
      { type: "TEXT", name: "Title", text: payload.title || "PROMO MLBB", fontSize: 86, bold: true, fill: payload.titleColor || "#ffffff", width: width - 144 },
      { type: "TEXT", name: "Subtitle", text: payload.subtitle || "Topup cepat, aman, dan murah.", fontSize: 36, fill: payload.textColor || "#d7e0ea", width: width - 144 },
      {
        type: "FRAME",
        name: "CTA Button",
        width: 340,
        height: 90,
        fill: payload.accent || "#ffcc33",
        cornerRadius: 999,
        autoLayout: { layoutMode: "HORIZONTAL", primaryAxisSizingMode: "AUTO", counterAxisSizingMode: "AUTO", paddingTop: 24, paddingRight: 34, paddingBottom: 24, paddingLeft: 34 },
        children: [{ type: "TEXT", name: "CTA", text: payload.cta || "ORDER SEKARANG", fontSize: 34, bold: true, fill: payload.background || "#101820" }],
      },
    ],
  };
  const frame = await createFrameFromSpec(spec, figma.currentPage);
  figma.viewport.scrollAndZoomIntoView([frame]);
  return { frameId: frame.id, name: frame.name };
}

async function createFrameSimple(payload) {
  var spec = withDefaults(payload, { type: "FRAME", fill: payload.background || payload.fill || "#ffffff" });
  spec.type = "FRAME";
  const frame = await createFrameFromSpec(spec, figma.currentPage);
  return { nodeId: frame.id };
}


// ===== plugin/src/modules/clone.js =====
async function applyPatchToNode(node, patch = {}) {
  if (!patch || typeof patch !== "object") return;
  if (typeof patch.name === "string") node.name = patch.name;
  if (typeof patch.x === "number") node.x = patch.x;
  if (typeof patch.y === "number") node.y = patch.y;
  if ("resize" in node && (patch.width || patch.height)) node.resize(patch.width || node.width, patch.height || node.height);
  if ("fills" in node && (patch.fill || patch.fills || patch.background)) node.fills = makePaints(patch.fills || patch.fill || patch.background);
  if ("strokes" in node && (patch.stroke || patch.strokes)) node.strokes = makePaints(patch.strokes || patch.stroke);
  if ("strokeWeight" in node && typeof patch.strokeWeight === "number") node.strokeWeight = patch.strokeWeight;
  if ("effects" in node && Array.isArray(patch.effects)) node.effects = patch.effects;
  if ("cornerRadius" in node && typeof patch.cornerRadius === "number") node.cornerRadius = patch.cornerRadius;
  if (node.type === "TEXT") {
    if (patch.fontName) node.fontName = await loadFont(patch.fontName);
    else await loadFont(node.fontName);
    if (typeof patch.text === "string" || typeof patch.characters === "string") node.characters = typeof patch.text === "string" ? patch.text : patch.characters;
    if (typeof patch.fontSize === "number") node.fontSize = patch.fontSize;
    if (patch.lineHeight) node.lineHeight = patch.lineHeight;
    if (patch.letterSpacing) node.letterSpacing = patch.letterSpacing;
    if (patch.textAlignHorizontal) node.textAlignHorizontal = patch.textAlignHorizontal;
    if (patch.textAlignVertical) node.textAlignVertical = patch.textAlignVertical;
  }
  if (patch.variableBindings) applyVariableBinding(node, { variableBindings: patch.variableBindings });
}

function findChildByName(parent, name) {
  if (!("children" in parent)) return null;
  for (const child of parent.children) {
    if (child.name === name) return child;
    if ("children" in child) {
      const nested = findChildByName(child, name);
      if (nested) return nested;
    }
  }
  return null;
}

function resolveTarget(root, target) {
  if (!target) return root;
  if (target.nodeId) return findNode(target.nodeId);
  if (target.byName) {
    const node = findChildByName(root, target.byName);
    if (!node) throw new Error(`Child not found by name: ${target.byName}`);
    return node;
  }
  return root;
}

async function cloneAndModify(payload) {
  await loadDefaultFonts();
  const source = findNode(payload.sourceNodeId);
  if (!("clone" in source)) throw new Error("Source node cannot be cloned");
  const clone = source.clone();
  if (typeof payload.name === "string") clone.name = payload.name;
  if (typeof payload.x === "number") clone.x = payload.x;
  if (typeof payload.y === "number") clone.y = payload.y;
  if (source.parent) source.parent.appendChild(clone);
  else figma.currentPage.appendChild(clone);

  for (const change of payload.changes || []) {
    const target = resolveTarget(clone, change.target);
    await applyPatchToNode(target, change.patch);
  }
  figma.viewport.scrollAndZoomIntoView([clone]);
  return { nodeId: clone.id, name: clone.name };
}

async function patchNode(payload) {
  const node = findNode(payload.nodeId);
  await applyPatchToNode(node, payload.patch || {});
  return { nodeId: node.id };
}


// ===== plugin/src/modules/exportOps.js =====
async function exportNodes(payload) {
  const ids = payload.nodeIds && payload.nodeIds.length ? payload.nodeIds : (payload.nodeId ? [payload.nodeId] : []);
  if (!ids.length) throw new Error("exportNodes needs nodeId or nodeIds");
  const settings = payload.settings || { format: "PNG", constraint: { type: "SCALE", value: 1 } };
  const exports = [];
  for (const id of ids) {
    const node = findNode(id);
    if (typeof node.exportAsync !== "function") throw new Error(`Node not exportable: ${id}`);
    const bytes = await node.exportAsync(settings);
    let base64 = "";
    const chunk = 0x8000;
    for (let i = 0; i < bytes.length; i += chunk) {
      base64 += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
    }
    exports.push({ nodeId: id, name: node.name, format: settings.format, base64: btoa(base64) });
  }
  return { exports };
}

function moveNode(payload) {
  const node = findNode(payload.nodeId);
  if (typeof payload.x === "number") node.x = payload.x;
  if (typeof payload.y === "number") node.y = payload.y;
  return { nodeId: node.id, x: node.x, y: node.y };
}

function resizeNode(payload) {
  const node = findNode(payload.nodeId);
  if (!("resize" in node)) throw new Error("Node is not resizable");
  node.resize(payload.width, payload.height);
  return { nodeId: node.id, width: node.width, height: node.height };
}

async function setText(payload) {
  const node = payload.nodeId ? findNode(payload.nodeId) : figma.createText();
  if (node.type !== "TEXT") throw new Error("Node is not text");
  node.fontName = await loadFont(payload.fontName || node.fontName);
  node.characters = payload.characters || "";
  if (!payload.nodeId) figma.currentPage.appendChild(node);
  return { nodeId: node.id };
}

function deleteNode(payload) {
  const node = findNode(payload.nodeId);
  node.remove();
  return { nodeId: payload.nodeId };
}


// ===== plugin/src/modules/events.js =====
// Module: events. Watches selection/page changes and forwards to UI for WS push.

function emitEvent(event) {
  figma.ui.postMessage({ type: "event", event });
}

function safeOn(eventName, handler) {
  try {
    figma.on(eventName, handler);
    log(`event listener enabled: ${eventName}`);
  } catch (error) {
    log(`event listener skipped: ${eventName} (${error.message})`);
  }
}

function setupEventForwarding() {
  safeOn("selectionchange", () => {
    const summaries = figma.currentPage.selection.map((node) => ({
      id: node.id,
      name: node.name,
      type: node.type,
      width: "width" in node ? node.width : null,
      height: "height" in node ? node.height : null,
    }));
    emitEvent({ type: "selectionChanged", selection: summaries, page: figma.currentPage.name });
  });

  safeOn("currentpagechange", () => {
    emitEvent({ type: "pageChanged", page: figma.currentPage.name, pageId: figma.currentPage.id });
  });

  safeOn("documentchange", (e) => {
    const counts = { CREATE: 0, DELETE: 0, PROPERTY_CHANGE: 0, STYLE_CREATE: 0, STYLE_DELETE: 0, STYLE_PROPERTY_CHANGE: 0 };
    const changes = e && Array.isArray(e.documentChanges) ? e.documentChanges : [];
    for (const change of changes) {
      if (counts[change.type] !== undefined) counts[change.type] += 1;
    }
    emitEvent({ type: "documentChanged", counts });
  });
}


// ===== plugin/src/modules/dispatcher.js =====
// Module: dispatcher. Maps command type -> handler. Handlers come from other modules.

const HANDLERS = {
  inspectSelection,
  inspectNode,
  getColorVariables: async () => ({ variables: await getColorVariables() }),
  createFromSpec,
  createPromoFrame,
  createFrame: createFrameSimple,
  cloneAndModify,
  patchNode,
  moveNode,
  resizeNode,
  setText,
  deleteNode,
  exportNodes,
};

async function applyCommand(command) {
  const handler = HANDLERS[command.type];
  if (!handler) throw new Error(`Unknown command type: ${command.type}`);
  return handler(command.payload || {});
}

async function postResult(result) {
  if (!state.bridgeUrl) return;
  await fetch(`${state.bridgeUrl}/results`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify(result),
  });
}

async function executeCommand(command) {
  log(`running ${command.type} (${command.id})`);
  try {
    const output = await applyCommand(command);
    await postResult({ id: command.id, ok: true, output });
    log(`done ${command.id}`);
    figma.ui.postMessage({
      type: "event",
      event: { type: "commandExecuted", commandId: command.id, commandType: command.type, ok: true },
    });
  } catch (error) {
    await postResult({ id: command.id, ok: false, error: error.message });
    log(`error ${command.id}: ${error.message}`);
    figma.ui.postMessage({
      type: "event",
      event: { type: "commandExecuted", commandId: command.id, commandType: command.type, ok: false, error: error.message },
    });
  }
}


// ===== plugin/src/modules/runtime.js =====
// Module: runtime. Main plugin owns HTTP command polling; UI owns WebSocket events.

figma.showUI(__html__, { width: 360, height: 460 });

try {
  setupEventForwarding();
} catch (error) {
  log(`event forwarding disabled: ${error.message}`);
}

async function fetchNextCommand() {
  try {
    const response = await fetch(`${state.bridgeUrl}/commands/next`, { headers: headers() });
    const data = await response.json();
    if (!data.command) return;
    await executeCommand(data.command);
  } catch (error) {
    log(`command poll error: ${error.message}`);
  }
}

function startCommandPolling() {
  if (state.timer) clearInterval(state.timer);
  state.timer = setInterval(fetchNextCommand, 1200);
  fetchNextCommand();
  log("HTTP command polling started");
}

function stopCommandPolling() {
  if (state.timer) clearInterval(state.timer);
  state.timer = null;
  log("HTTP command polling stopped");
}

figma.ui.onmessage = async (msg) => {
  if (!msg || !msg.type) return;
  if (msg.type === "configure") {
    state.bridgeUrl = msg.bridgeUrl || state.bridgeUrl;
    state.secret = msg.secret || "";
    log("configured: " + state.bridgeUrl);
    return;
  }
  if (msg.type === "startPolling") {
    state.bridgeUrl = msg.bridgeUrl || state.bridgeUrl;
    state.secret = msg.secret || "";
    startCommandPolling();
    return;
  }
  if (msg.type === "stopPolling") {
    stopCommandPolling();
    return;
  }
  if (msg.type === "pollNow") {
    await fetchNextCommand();
    return;
  }
  if (msg.type === "stop") {
    log("stopped");
    return;
  }
  if (msg.type === "command" && msg.command) {
    if (msg.bridgeUrl) state.bridgeUrl = msg.bridgeUrl;
    if (msg.secret !== undefined) state.secret = msg.secret;
    await executeCommand(msg.command);
    return;
  }
};

